-- Select the database
USE alx_book_store;

-- Drop tables if they exist (reverse order of dependencies)
DROP TABLE IF EXISTS order_details;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS customers;-- Authors table
CREATE TABLE AUTHORS (
    AUTHOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    BIO TEXT
);

-- Books table
CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR_ID INT,
    PRICE DECIMAL(10,2),
    STOCK INT DEFAULT 0,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

-- Customers table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    PHONE VARCHAR(20),
    ADDRESS TEXT
);

-- Orders table
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    ORDER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    TOTAL DECIMAL(10,2) DEFAULT 0,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Order Details table
CREATE TABLE ORDER_DETAILS (
    ORDER_DETAIL_ID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT,
    BOOK_ID INT,
    QUANTITY INT DEFAULT 1,
    PRICE DECIMAL(10,2),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);